- src/AppBundle/Resources/views/Email/report-submission-confirm.html.twig
- src/AppBundle/Resources/views/Email/report-submission-confirm.text.twig
Update email content so users understand they can download and review this report, and that they don't have to make an immediate start on the next report.
> Content update submission confirm

- src/AppBundle/Controller/Odr/AccountController.php
- src/AppBundle/Controller/Report/AccountController.php
- src/AppBundle/Entity/Odr/BankAccount.php
- src/AppBundle/Entity/Report/BankAccount.php
There was an assumption that bank account types which didn't require a sort code ALSO didn't require a bank account name, but this is incorrect: the type 'other_no_sortcode' requires no sort code but still requires a bank name
SO work done to turn the requiresBankNameAndSortCode() function into separate requiresBankName() and requiresSortCode() functions
> DDPB-750 bank account name

- Dockerfile
same as of https://github.com/ministryofjustice/opg-digi-deps-client/pull/842
This PR aims to shrink the ```docker build . ``` times to negative values.
Not there yet, but locally I achieved some good results:
my baseline
On jenkins, the 01_Build_Docker_Images job averages around 30minutes
locally:
```
time docker build --no-cache .
real    9m10.764s
user    0m0.239s
sys     0m0.053s
```
with these changes:
```
time docker build --no-cache .
real    1m33.546s
user    0m0.230s
sys     0m0.049s
```
jenkins jobs:
(25 min) with these changes:
https://jenkins.service.opg.digital/job/Digi-Deps/job/01_Build_Docker_Images/659/console
(4 min) With these changes + https://github.com/ministryofjustice/opg-digi-deps-client/pull/842 + https://github.com/ministryofjustice/opg-digi-deps-docker/pull/60 …
> DDPB-1764 parallel install of composer deps

- Dockerfile
- Dockerfile.base
See: https://github.com/ministryofjustice/opg-digi-deps-docker/pull/61
This PR splits the Dockerfile into a nightly build using a Dockerfile.base and the normal build which will consume a FROM: nnnnn-base:nightly.
> DDPB-1764: split Dockerfile and add a nightly Dockerfile.base

- app/DoctrineMigrations/Version208.php
- src/AppBundle/Controller/Report/ReportController.php
- src/AppBundle/Entity/Report/Traits/ReportProfDeputyCostsTrait.php
- src/AppBundle/Service/ReportStatusService.php
- tests/AppBundle/Service/ReportStatusServiceTest.php
Removes `profDeputyCostsHowChargedAgreed` property from `ReportProfDeputyCostsTrait` and drops references to it in the API responses and tests.
The [client PR](https://github.com/ministryofjustice/opg-digi-deps-client/pull/1148) should be merged before this to ensure that the client isn't making reference to these fields once they're removed.
> DDPB-2468 Remove Agreed costs option from 105

- src/AppBundle/Entity/Report/Traits/ReportProfDeputyCostsEstimateTrait.php
The other side of the validation fix to ensure the JMS group types match (see [client PR](https://github.com/ministryofjustice/opg-digi-deps-client/pull/1162)).
> Validation fix

- docker/confd/templates/parameters.yml.tmpl
- src/AppBundle/Command/AddSingleUserCommand.php
- src/AppBundle/Command/FixturesCommand.php
- tests/AppBundle/Controller/ClientControllerTest.php
In DDPB-2517, we are adding new user accounts to test fixtures to allow testers to easily log in as professional and PA deputies.
Supporting these new deputy types requires some changes to the `AddSingleUserCommand` command:
* Assigning deputies to teams
* Allowing multiple deputies to be assigned to the same client
* Automatically generating reports for professional and PA deputies (because that drives the dashboard)
>  DDPB-2517: Allow more complex users in test fixtures

- src/AppBundle/Controller/ClientController.php
- src/AppBundle/Entity/Report/Report.php
- src/AppBundle/Service/ReportStatusService.php
- tests/AppBundle/Controller/AbstractTestController.php
- tests/AppBundle/Controller/CasRecControllerTest.php
- tests/AppBundle/Controller/ClientControllerTest.php
- tests/AppBundle/Controller/PaControllerTest.php
- tests/AppBundle/Controller/SettingControllerTest.php
- tests/AppBundle/Entity/Repository/ReportRepositoryTest.php
- tests/AppBundle/Service/CasrecServiceTest.php
- tests/AppBundle/Service/OrgServiceTest.php
- tests/Fixtures.php
I've moved the NDR creation step to the Lay Deputy specific steps during the upsert action to ensure they are only created for Lay Deputies.
As I was running the unit tests locally I encountered an error while loading the fixtures class so I've namespaced this and updated references as part of this PR.
> DDPB-2512 - NDR report incorrectly displayed

- app/config/services.yml
- src/AppBundle/DataFixtures/UserPasswordFixtures.php
Removing auto-wiring means that you don't have to define the fixture parameter to start the application. Environments which define the parameter can load fixtures, but those which don't can't.
> DDBP-2524: Load fixture parameter on demand

- src/AppBundle/Controller/CoDeputyController.php
- src/AppBundle/Controller/UserController.php
- src/AppBundle/Service/UserService.php
The requirement is to ensure that an NDR gets created when NDR is enabled via the user edit page in admin. We also need to ensure that if it is re-enabled, then it does not create a new NDR. I.e, only create NDR if one does not already exist.
Small refactor of the method:
* Removed unused parameter
* Removed unused code
* Moved exception checking into a method
> DDPB 2631 NDR creation on enabling

- ROLLBACK-PROCEDURE.md
- app/DoctrineMigrations/Version182.php
- app/DoctrineMigrations/Version183.php
- app/DoctrineMigrations/Version186.php
- app/DoctrineMigrations/Version193.php
- app/DoctrineMigrations/Version196.php
- app/DoctrineMigrations/Version198.php
- app/DoctrineMigrations/Version201.php
- app/DoctrineMigrations/Version204.php
- app/DoctrineMigrations/Version205.php
- app/DoctrineMigrations/Version206.php
- app/DoctrineMigrations/Version207.php
- app/DoctrineMigrations/Version208.php
- app/DoctrineMigrations/Version210.php
- app/DoctrineMigrations/Version211.php
- app/DoctrineMigrations/Version212.php
- app/config/services.yml
- app/config/services/event_listeners.yml
- scripts/apiunittest.sh
- src/AppBundle/EventListener/FixDefaultSchemaListener.php
Down migrations generated by Doctrine include a `CREATE SCHEMA public` command. This is erroneous and causes the down migrations to fail (because the public schema already exists).
This is [a known issue](https://github.com/doctrine/dbal/issues/1110) in Doctrine DBAL.
I removed the `CREATE SCHEMA public` command from existing migrations, and also introduced a listener which stops them from being added unless necessary (e.g. if we start using multiple schemas).
I took the fix from [a comment on the GitHub issue](https://github.com/doctrine/dbal/issues/1110#issuecomment-255765189). This seems to be the accepted solution for now, awaiting Doctrine to fix the issue permanently.
- [N/A] I have updated documentation (Confluence/GitHub wiki) where relevant
- [N/A] I have added tests to prove my …
> Don't add `CREATE SCHEMA public` commands to down migrations

- app/bootstrap.php.cache
- composer.lock
- src/AppBundle/DataFixtures/UserFixtures.php
PMs want a test account with access to the "invite a codeputy" flow, so they can easily test clients with multiple deputies.
Fixes [DDPB-2617](https://opgtransform.atlassian.net/browse/DDPB-2617)
I've added a new fixture user with the `coDeputyClientConfirmed` property. This gives them access to the new codeputy portal.
_N/A_
- Updated [fixture user list](https://opgtransform.atlassian.net/wiki/spaces/DigiDeps/pages/1070334023/Testing)
- N/A, not present in production
- Symfony upgraded to v3.4.26 to escape 5 security issues present in v3.4.24
> DDPB-2617: Create a test account for a lay deputy with a co deputy

- src/AppBundle/Controller/ManageController.php
We recently had an issue identifying what configuration environment we'd deployed to a server. This will make it easier to determine that in the future by displaying the environment clearly on the availability page.
Fixes [DDPB-2656](https://opgtransform.atlassian.net/browse/DDPB-2656)
I added `$kernel->getEnvironment()` to the response object.
- [N/A] I have added tests to prove my work, and they follow our [best practices](https://github.com/ministryofjustice/opg-digi-deps-client/wiki/Testing-best-practices)
- [N/A] The product team have tested these changes
> Expose the environment on the API availability page

- src/AppBundle/DataFixtures/UserFixtures.php
Fixture code currently creates CasRec records for all deputies, but only lay deputies should be included. This causes issues when generating next year's report because it tries to identify a CasRec record to identify the report type.
Fixes an issue identified as part of DDPB-2648.
The fixtures now only creates a CasRec entry for lay deputies.
The issue was originally caused by not recognising how CasRec works when implementing the new fixtures. This highlights the important of business knowledge in technical changes.
- N/A
> Only create fixture CasRec records for lay deputies

- app/config/config_test.yml
Prevent Symfony test env from using mock file system in order to cope with running the test suite across multiple api and frontend instances.
Fixes [DDPB-2661](https://opgtransform.atlassian.net/browse/DDPB-2661)
Removing the session directive from config_test.yml enables the session storage to fall back to the redis storage due to the fact config_test.yml inherits from config_prod.yml
None
- [N/A] I have updated documentation (Confluence/GitHub wiki) where relevant
- [N/A] There are no Composer security issues (`docker-compose run api php app/console security:check`)
> DDPB-2661: replaces file based session storage in test env with redis

- src/AppBundle/Controller/BehatController.php
The Behat controllers are used for debugging and test automation in non-production environments. However, due to a misconfiguration, they are currently available in production too.
Fixes [DDPB-2679](https://opgtransform.atlassian.net/browse/DDPB-2679)
The controller now properly throws an exception rather than returning it (the parent function was ignoring it).
> DDBP-2679: Hide Behat controller in production

- src/AppBundle/Entity/Report/MoneyTransaction.php
To enable the displaying of category text based on the user role. 
Fixes [DDPB-2658](https://opgtransform.atlassian.net/browse/DDPB-2658)
The client side now has two category types, one for lay and one for non lay. To ensure the new types are returned in API calls, we need to add the new type strings to MoneyTransaction on the API side.
- [N/A] I have updated documentation (Confluence/GitHub wiki) where relevant
- [N/A] I have added tests to prove my work, and they follow our [best practices](https://github.com/ministryofjustice/opg-digi-deps-client/wiki/Testing-best-practices)
> DDPB-2658: Adds lay and non lay specific money out category

- app/config/config_dev.yml
- app/config/config_test.yml
- app/config/routing_dev.yml
The API config files have both of duplication and unnecessary rules. This obscures the actual configuration of the environment, and makes future config changes more risky.
Fixes [DDPB-2637](https://opgtransform.atlassian.net/browse/DDPB-2637)
I switched both `config_dev` and `config_test` to build off of `config_prod` so that any changes to the production configuration also affect dev and test ones.
I removed any duplication, and any rules which were unnecessary (e.g. the extra routing rules didn't do anything and the extra profiler rules have no effect because the profiler is disabled).
Nothing particularly interesting.
- N/A, no outward facing changes
> DDPB-2637: Tidy up API config files

- Dockerfile
- composer.json
- composer.lock
- docker/confd/conf.d/php.ini.toml
- docker/confd/templates/php.ini.tmpl
- docker/confd/templates/xdebug.ini.tmpl
- src/AppBundle/Command/CleanDataCommand.php
- src/AppBundle/Command/MigrationsMigrateLockCommand.php
- src/AppBundle/Controller/ClientContactController.php
- src/AppBundle/Controller/ManageController.php
- src/AppBundle/Controller/NoteController.php
- src/AppBundle/Controller/OrgController.php
- src/AppBundle/Controller/SelfRegisterController.php
- src/AppBundle/Entity/User.php
- src/AppBundle/Service/CasrecService.php
- src/AppBundle/Service/OrgService.php
- src/AppBundle/Service/UserRegistrationService.php
PHP 5.x has reached EOL, so we need to upgrade to PHP 7.
Fixes [DDPB-2629](https://opgtransform.atlassian.net/browse/DDPB-2629)
The fundamental changes here are pretty straightforward: use PHP7 base images in the Dockerfile and simplify the extension configuration now that we can use the latest versions.
A few other changes:
- Upgraded `doctrine/orm` since ≤2.5 is only compatible with PHP5 and ≥2.6 is only compatible with PHP7
- Removed `zend_extension` configuration strings since these are done as part of `docker-php-ext-install` and `docker-php-ext-enable`
- Removed an unsupported argument to `time()` (PHP is fussy about this now)
- Replaced `catch (\Exception)` with `catch (\Throwable)` to [respect changes in PHP7](https://www.php.net/manual/en/language.errors.php7.php)
We should …
> DDPB-2629: Upgrade PHP to 7.3

- src/AppBundle/Entity/Report/Traits/FeeExpensesTrait.php
If a PA deputy adds a expense to a report, then the report overview page crashes.
This is due to a bug with `FeeExpensesTrait`, which has a double-count in it (effectively `count(count($expenses))`). In PHP5 this was skipped over, but PHP7 throws a fatal error when asked to count an integer.
Fixes [DDPB-2742](https://opgtransform.atlassian.net/browse/DDPB-2742)
I removed the second `count` function.
We were already aware of this problem, but weren't able to identify every scenario it occurred in. Fortunately it was easy to identify from errors logs in CloudWatch.
> DDPB-2742: PA client overview page inaccessible after expenses added

- src/AppBundle/Controller/BehatController.php
- src/AppBundle/DataFixtures/UserFixtures.php
Reduce the dependancy on behat-user that is created by a test. This in turn reduces the interdependency of tests requiring other tests to run.
Fixes [DDPB-2624]
Ive used the appropriate fixture users to replace the instances of behat-user with those required for the report being tested. So behat-lay-deputy-102 for 102 report, 103 for 103 report etc. The behat user is still used for ttesting CASREC and creating users and cross checks.
As we were using a different deputy, then the client also changed so many tests needed to be updated with content associated with the new client.
When switching between different report types, we simply change the report type as needed, to avoid retesting sections already completed. This had a knock on effect in that when changing report type, I updated the …
> Ddpb 2624 fixture users in tests

- docs/TECH_DEBT.md
- docs/pull_request_template.md
We want to record known technical debt in DigiDeps.
I created a document to record tech debt (and [another in client](https://github.com/ministryofjustice/opg-digi-deps-client/pull/1288)). I also added it as a documentation option in our PR template.
> Add technical debt document

- src/AppBundle/Controller/BehatController.php
Due to our client side changes, we no longer need the `/behat/client` route.
Fixes [DDPB-2797](https://opgtransform.atlassian.net/browse/DDPB-2797)
I removed the action.
- N/A
> DDPB-2797: Remove `/behat/client` route
