app/config/parameters.yml.dist
app/config/services.yml
docker/confd/conf.d/parameters.hml.toml
docker/confd/templates/parameters.yml.tmpl
src/AppBundle/Controller/EmailController.php

@munhitsu please review the changes (only inside "docker" dir) along with pull req on DOCKER repo.
DO NOT MERGE YET

dd-861 remove sendgrid, enable 2nd smtp

---

Dockerfile
docker/confd/conf.d/nginx.app.conf.toml
docker/confd/templates/nginx.app.conf.tmpl
docker/nginx/app.conf
scripts/database.sh
scripts/resetdb.sh

merge dev->master

---

src/AppBundle/Entity/Asset.php

report.noASsetsToAdd is now set in the model directly (no API call needed)

dd-1085 new asset 

---

README.md
src/AppBundle/Entity/CasRec.php
src/AppBundle/Entity/Client.php
src/AppBundle/Service/UserRegistrationService.php
tests/phpunit/Controller/AbstractTestController.php
tests/phpunit/Controller/SelfRegisterControllerTest.php
tests/phpunit/Entity/CasRecTest.php
tests/phpunit/Service/UserRegistrationServiceTest.php

dd-1206 user registraion not allowed if caseNumber already used + data match improvements

---

app/DoctrineMigrations/Version053.php
scripts/database.sh
src/AppBundle/Entity/Report.php
src/AppBundle/Entity/Transaction.php
src/AppBundle/Service/DataMigration/AccountMigration.php
src/AppBundle/Service/Mailer/MessageUtils.php
tests/phpunit/DataMigration/Account/AccountMigrationTest.php
tests/phpunit/src/Controller/AbstractTestController.php
tests/phpunit/src/Controller/ReportControllerTest.php
tests/phpunit/src/Controller/StatsControllerTest.php
tests/phpunit/src/Entity/ReportRepositoryTest.php
tests/phpunit/src/Fixtures.php
tests/phpunit/src/Resources/Report/Formatted/AccountsTest.php
tests/phpunit/src/Service/Mailer/MessageUtilsTest.php
tests/phpunit/src/bootstrap.php
tests/phpunit/src/phpunit.xml

fix missing transactions (migration unit-tsted)
fix order
fix phpunit tests
phpunit tests not clear data before each tests using pg import (more independent runs)

Report fixes

---

app/config/parameters.yml.dist
docker/confd/templates/parameters.yml.tmpl
src/AppBundle/Service/Mailer/MailFactory.php

report confirmation email link goes to client homepage

---

app/DoctrineMigrations/Version097.php
app/DoctrineMigrations/Version098.php
src/AppBundle/Controller/Report/MentalCapacityController.php
src/AppBundle/Entity/Report/MentalCapacity.php
tests/AppBundle/Controller/Report/MentalCapacityControllerTest.php

Added the mental assessment date field.

Mental assessment date entity field

---

Dockerfile
scripts/backupdbToS3.sh
scripts/resetdb.sh
scripts/restoredbFromS3.sh

* Scripts changed to accept an env var or fail back to old default

Opgops 1601

---

Dockerfile
docker/beaver.d/application.conf
docker/confd/conf.d/beaver.application.conf.toml
docker/confd/templates/beaver.application.conf.tmpl

* Updated docker image to 0.1.215 
* Updated logging tags 
closes #284

Opgops 1883

---

app/config/security.yml
src/AppBundle/Controller/Report/AccountController.php
src/AppBundle/Controller/Report/ActionController.php
src/AppBundle/Controller/Report/AssetController.php
src/AppBundle/Controller/Report/ContactController.php
src/AppBundle/Controller/Report/DecisionController.php
src/AppBundle/Controller/Report/ExpenseController.php
src/AppBundle/Controller/Report/GiftController.php
src/AppBundle/Controller/Report/MentalCapacityController.php
src/AppBundle/Controller/Report/MoneyTransactionController.php
src/AppBundle/Controller/Report/MoneyTransactionShortController.php
src/AppBundle/Controller/Report/MoneyTransferController.php
src/AppBundle/Controller/Report/ReportController.php
src/AppBundle/Controller/Report/VisitsCareController.php
src/AppBundle/Entity/User.php
src/AppBundle/Service/PaService.php
tests/AppBundle/Controller/Report/ReportControllerTest.php

Uses role hierarchy to simplify access checks

DDPB-1146: PA user can edit reports

---

src/AppBundle/Controller/Report/NoteController.php
src/AppBundle/Entity/Report/Report.php

Note align

---

src/AppBundle/Controller/UserController.php

When a PA updates their address, the team address plus the other PAs addresses are changed to same

DDPB-1447 - Same Address for PA team on PA user update

---

src/AppBundle/Controller/Report/ReportController.php

As per other sections eg Assets, transactions, gifts…

DDPB-1400-bugfix Answering ‘no documents’ deletes existing docs

---

src/AppBundle/Controller/Report/ReportController.php

no longer deletes attached uploads

DDPB-1400 Answering no with docs

---

src/AppBundle/Controller/UserController.php
tests/AppBundle/Controller/UserControllerTest.php

Reverts ministryofjustice/opg-digi-deps-api#391

Revert "Ddpb 1626 deny admin password reset"

---

src/AppBundle/Controller/Report/ReportController.php

Produces more consistent ordering where report end dates are identical

Add secondary sort to dashboard

---

src/AppBundle/Controller/Report/ReportSubmissionController.php
src/AppBundle/Entity/Repository/ReportSubmissionRepository.php
tests/AppBundle/Controller-Report/ReportSubmissionControllerTest.php

JIRA: [DDPB-2359](https://opgtransform.atlassian.net/browse/DDPB-2359)
```
root@4d0265a9e989:/app# php vendor/phpunit/phpunit/phpunit -c tests/phpunit.xml tests/AppBundle/Controller-Report/
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.
...............................................................  63 / 122 ( 51%)
..................................................SSSSSSSSS
Time: 3.68 minutes, Memory: 771.00MB
OK, but incomplete, skipped, or risky tests!
Tests: 113, Assertions: 1500, Skipped: 9.
```

DDPB-2359: Adds toDate filter to report-submission/casrec_data

---

src/AppBundle/Controller/TeamController.php
src/AppBundle/Entity/User.php

https://opgtransform.atlassian.net/browse/DDPB-2415

DDPB-2415: Fixes deputy list timeout

---

src/AppBundle/Controller/Report/ReportSubmissionController.php
src/AppBundle/Entity/Repository/ReportSubmissionRepository.php

Removes the limit/offset functionality which was restricted the results. Limiting not necessary here.

DDPB-2442: Removes SQL LIMIT on Report Submissions stats query

---

src/AppBundle/Controller/UserController.php

DDPB 2430 admin search improvements

---

app/DoctrineMigrations/Version210.php
src/AppBundle/Controller/Report/ReportController.php
src/AppBundle/Entity/Report/Checklist.php

Adds support for a new `nextBillingEstimatesSatisfactory` field to indicate if the admin is satisfied with the cost estimates provided by the deputy.

DDPB-2467: Add estimates question to checklist

---

src/AppBundle/Service/ReportStatusService.php

Don't require SCCO section to be completed if the deputy has only submitted fixed costs.

DDPB 2506: Deputy costs asking for SCCO figure with fixed costs

---

scripts/cron/digideps

https://opgtransform.atlassian.net/browse/DDPB-2514

DDPB-2514: Prevent digideps:stats-update command from running by cron

---

docker/confd/templates/parameters.yml.tmpl
src/AppBundle/Command/AddSingleUserCommand.php
src/AppBundle/Command/FixturesCommand.php
tests/AppBundle/Controller/ClientControllerTest.php

 DDPB-2517: Add new users to feature-105 branch

---

app/DoctrineMigrations/Version204.php
src/AppBundle/Controller/Report/ReportController.php
src/AppBundle/Entity/Report/Checklist.php

Adds the new `deputyChargeAllowedByCourt` question to the checklist

DDPB-2412 Change PA checklist question
